### ISSUE TITLE
Taking too much memory

### ISSUE THREAD

**Issue by aakash-saboo** [devzhk/Implicit-Competitive-Regularization#12]
The optimizer is taking almost 5x memory as compared to adam optimizer.
In my code, adam optimizer takes around 4 gb but this optimizer takes 18gb.
Is it normal?

**Comment by devzhk** [comment]
It is supposed to take 3x memory as compared to Adam. Extra memory cost can be reduced by better  implementation. e.g. implement it in C++ and optimize memory allocation.
