### ISSUE TITLE
cifar10.py

### ISSUE THREAD

**Issue by zr-bee** [devzhk/Implicit-Competitive-Regularization#16]
Is the tflib.fid in cifar10.py a custom library, is it missing?

**Comment by devzhk** [comment]
Hey, 
The `metrics` directory contains files including cifar10.py are designed to compute FID (Fréchet Inception Distance) and IS (Inception Score) metrics.
As of 2023, there are much better options for computing these metrics. If you are using PyTorch, I would suggest using the [clean-fid package](https://github.com/GaParmar/clean-fid). On the other hand, if you are a TensorFlow user, the evaluation code available in the [ADM repo](https://github.com/openai/guided-diffusion/tree/main/evaluations) from OpenAI's Guided Diffusion may be more suitable.

**Comment by zr-bee** [comment]
hey，Thanking your reply.
I have other problem:&nbsp;
eval_pt-cifar10-dc.sh，Where checkpoints/cifar-ACGD/ACGD-dc0.010_ is obtained, it looks a bit mixed.Or my own level is relatively low







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "devzhk/Implicit-Competitive-Regularization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 凌晨0:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [devzhk/Implicit-Competitive-Regularization] cifar10.py (Issue #16)





 
Hey,
 The metrics directory contains files including cifar10.py are designed to compute FID (Fréchet Inception Distance) and IS (Inception Score) metrics.
 As of 2023, there are much better options for computing these metrics. If you are using PyTorch, I would suggest using the clean-fid package. On the other hand, if you are a TensorFlow user, the evaluation code available in the ADM repo from OpenAI's Guided Diffusion may be more suitable.
