### ISSUE TITLE
cannot import name 'CGD'

### ISSUE THREAD

**Issue by Johnson-yue** [devzhk/Implicit-Competitive-Regularization#2]
Hi, thank you for sharing your code.  I will run train.ipynb  not it is error

than I check file `VisionData.py` and `optimizers.py`  I found:

In `VisionData.py`  you import **CGD** module but  in  `optimizers.py` only have  **BCGD, OCGD, MCGD** , also miss **ACGD**

**Comment by devzhk** [comment]
I forgot to remove the unnecessary import. I removed it just now. And yes, class name is a little confusing. I renamed the class to be consistent with the name in paper. 

Thanks !
