### ISSUE TITLE
single '}' is redundant !!

### ISSUE THREAD

**Issue by Johnson-yue** [devzhk/Implicit-Competitive-Regularization#3]
Hi, I run the `train.ipynb`  and has error than I check the VisionData.py code 

error: in this [line code](https://github.com/devzhk/Implicit-Competitive-Regularization/blob/3a9505f196a578a7a03aa44548a412defe760afe/VisionData.py#L337)

your repo : 
> print('inception score- mean: {}}, std: {}'.format(is_mean, is_std)) 

should be inplace with :  

> print('inception score- mean: {}, std: {}'.format(is_mean, is_std))

**Comment by devzhk** [comment]
Sorry, I uploaded the wrong file. The latest version fix the problem.
