### ISSUE TITLE
IF I have two Discriminator  how to use ACGD ?

### ISSUE THREAD

**Issue by Johnson-yue** [devzhk/Implicit-Competitive-Regularization#5]
![image](https://user-images.githubusercontent.com/10268274/67498003-5f4c7000-f6b1-11e9-8683-400c5521ebb4.png)
In readMe , it is only One G and One D, so if I have **Two** D or **Two** G, how to use it?

**Comment by devzhk** [comment]
Good question! But I'm sorry current ACGD doesn't support Multi-Discriminator or Multi-Generator settings. It would be an interesting point for future work.

**Comment by Johnson-yue** [comment]
I am so interested in you work ,so I have a requested about your code , and I look forward to you update your repo for results with other datasets

**Comment by devzhk** [comment]
Cool, will do!
